### ISSUE TITLE
margin notes can collide with each other

### ISSUE THREAD

**Issue by jsmaniac** [racket/scribble#120]
When two margin notes are defined close to each other, they can overlap in the HTML version (in the example below, `Hello` and `world` are typeset above one another).

```
#lang scribble/manual
@(require scriblib/footnote)
Foo@note{Hello} bar@note{world}.
```

On chromium, I can fix this by changing in https://github.com/racket/scribble/blob/master/scribble-lib/scriblib/footnote.css

```css
.NoteBox {
  …
  height: 0em;
  …
}
```

to

```css
.NoteBox {
  …
  height: auto;
  clear: right;
  …
}
```

Is there any particular reason for having this `height: 0em` in the first place (e.g. compatibility with an older/another browser)?

If this change seems correct, I can submit a PR.
